/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eap.pli24.weatherapp.gui;

import com.eap.pli24.weatherapp.db.CityForecast;
import com.eap.pli24.weatherapp.db.MyJpaLinker;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



public class CityForecastEditForm extends javax.swing.JFrame {
    
    private MyJpaLinker jpaLinker;
    
    CityForecast forecast = null;
    CityForecast editedForecast = new CityForecast();
       
    /**
     * Creates new form CityForecastEditForm
     */
    public CityForecastEditForm() {
        
        setTitle("Επεξεργασία Δεδομένων Πόλεων");
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.jpaLinker = new MyJpaLinker();
        fillWithDatesComboBox();
        
        if (dateSelectionJComboBox.getItemCount() > 0) {
            String selectedDate = (String) dateSelectionJComboBox.getItemAt(0);
            jpaLinker.populateCityList(citiesJList, selectedDate);
        }
                
        
        citiesJList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    String selectedDate = (String) dateSelectionJComboBox.getSelectedItem();
                    String selectedCity = citiesJList.getSelectedValue();
                    if (selectedDate != null && selectedCity != null) {
                        displayForecast(selectedDate, selectedCity);
                    }
                }
            }
        });
        
        dateSelectionJComboBox.addActionListener(new ActionListener() {
           
            public void actionPerformed(ActionEvent event) {
                String selectedDate = (String) dateSelectionJComboBox.getSelectedItem();
                if (selectedDate != null) {                    
                    jpaLinker.populateCityList(citiesJList, selectedDate);                                        
                }
            }
        });        
        
    }
    
    
    
    private void fillWithDatesComboBox() {
        this.jpaLinker.fillWithDatesJcomboBox(dateSelectionJComboBox);
    }

    private void displayForecast(String selectedDate, String selectedCity) {
        
        this.forecast = jpaLinker.getForecastFromDB(selectedDate, selectedCity);

        if (forecast != null) {
            editTemperatureJTextField.setText(String.valueOf(forecast.getTemperature()));
            editHumidityJTextField.setText(String.valueOf(forecast.getHumidity()));
            editUVIndexJTextField.setText(String.valueOf(forecast.getUvindex()));
            editWindSpeedJTextField.setText(String.valueOf(forecast.getWindspeed()));
            editWeatherDescJTextField.setText(forecast.getWeatherdescription());
        } else {
            
            editTemperatureJTextField.setText("");
            editHumidityJTextField.setText("");
            editUVIndexJTextField.setText("");
            editWindSpeedJTextField.setText("");
            editWeatherDescJTextField.setText("");
        }
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editForecastJpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        editTemperatureJLabel = new javax.swing.JLabel();
        editHumidityJLabel = new javax.swing.JLabel();
        editUvIndexJLabel = new javax.swing.JLabel();
        editWindJLabel = new javax.swing.JLabel();
        editWeatherDescriptionJLabel = new javax.swing.JLabel();
        editTemperatureJTextField = new javax.swing.JTextField();
        editHumidityJTextField = new javax.swing.JTextField();
        editUVIndexJTextField = new javax.swing.JTextField();
        editWindSpeedJTextField = new javax.swing.JTextField();
        editWeatherDescJTextField = new javax.swing.JTextField();
        editForecastInDBjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        citiesJList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        dateSelectionJComboBox = new javax.swing.JComboBox<>();
        datejLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Forecast");
        setName("editForecastFrame"); // NOI18N

        editForecastJpanel.setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editTemperatureJLabel.setBackground(new java.awt.Color(0, 102, 51));
        editTemperatureJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editTemperatureJLabel.setForeground(new java.awt.Color(255, 255, 255));
        editTemperatureJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editTemperatureJLabel.setText("Θερμοκρασία:");
        editTemperatureJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editTemperatureJLabel.setMaximumSize(new java.awt.Dimension(139, 24));
        editTemperatureJLabel.setMinimumSize(new java.awt.Dimension(139, 24));
        editTemperatureJLabel.setPreferredSize(new java.awt.Dimension(139, 24));

        editHumidityJLabel.setBackground(new java.awt.Color(0, 102, 51));
        editHumidityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editHumidityJLabel.setForeground(new java.awt.Color(255, 255, 255));
        editHumidityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editHumidityJLabel.setText("Υγρασία:");
        editHumidityJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editHumidityJLabel.setMaximumSize(new java.awt.Dimension(139, 24));
        editHumidityJLabel.setMinimumSize(new java.awt.Dimension(139, 24));
        editHumidityJLabel.setPreferredSize(new java.awt.Dimension(139, 24));

        editUvIndexJLabel.setBackground(new java.awt.Color(0, 102, 51));
        editUvIndexJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editUvIndexJLabel.setForeground(new java.awt.Color(255, 255, 255));
        editUvIndexJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editUvIndexJLabel.setText("UV Δέικτης:");
        editUvIndexJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editUvIndexJLabel.setMaximumSize(new java.awt.Dimension(139, 24));
        editUvIndexJLabel.setMinimumSize(new java.awt.Dimension(139, 24));
        editUvIndexJLabel.setPreferredSize(new java.awt.Dimension(139, 24));

        editWindJLabel.setBackground(new java.awt.Color(0, 102, 51));
        editWindJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editWindJLabel.setForeground(new java.awt.Color(255, 255, 255));
        editWindJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editWindJLabel.setText("Ταχύτητα Ανέμου:");
        editWindJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editWindJLabel.setMaximumSize(new java.awt.Dimension(139, 24));
        editWindJLabel.setMinimumSize(new java.awt.Dimension(139, 24));
        editWindJLabel.setPreferredSize(new java.awt.Dimension(139, 24));

        editWeatherDescriptionJLabel.setBackground(new java.awt.Color(0, 102, 51));
        editWeatherDescriptionJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editWeatherDescriptionJLabel.setForeground(new java.awt.Color(255, 255, 255));
        editWeatherDescriptionJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editWeatherDescriptionJLabel.setText("Περιγραφή Καιρού:");
        editWeatherDescriptionJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editTemperatureJTextField.setBackground(new java.awt.Color(204, 204, 204));
        editTemperatureJTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editTemperatureJTextField.setForeground(new java.awt.Color(0, 0, 0));
        editTemperatureJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editHumidityJTextField.setBackground(new java.awt.Color(204, 204, 204));
        editHumidityJTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editHumidityJTextField.setForeground(new java.awt.Color(0, 0, 0));
        editHumidityJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editUVIndexJTextField.setBackground(new java.awt.Color(204, 204, 204));
        editUVIndexJTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editUVIndexJTextField.setForeground(new java.awt.Color(0, 0, 0));
        editUVIndexJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editWindSpeedJTextField.setBackground(new java.awt.Color(204, 204, 204));
        editWindSpeedJTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editWindSpeedJTextField.setForeground(new java.awt.Color(0, 0, 0));
        editWindSpeedJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editWeatherDescJTextField.setBackground(new java.awt.Color(204, 204, 204));
        editWeatherDescJTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editWeatherDescJTextField.setForeground(new java.awt.Color(0, 0, 0));
        editWeatherDescJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editTemperatureJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editHumidityJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editWindJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editUvIndexJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editWeatherDescriptionJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editWindSpeedJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(editWeatherDescJTextField)
                    .addComponent(editHumidityJTextField)
                    .addComponent(editUVIndexJTextField)
                    .addComponent(editTemperatureJTextField))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editTemperatureJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(editTemperatureJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editHumidityJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editHumidityJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editUVIndexJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(editUvIndexJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editWindJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editWindSpeedJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editWeatherDescriptionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editWeatherDescJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        editForecastInDBjButton.setBackground(new java.awt.Color(102, 102, 102));
        editForecastInDBjButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editForecastInDBjButton.setForeground(new java.awt.Color(255, 255, 255));
        editForecastInDBjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eap/pli24/weatherapp/resources/save-alt.30x27.png"))); // NOI18N
        editForecastInDBjButton.setText("Αποθήκευση");
        editForecastInDBjButton.setToolTipText("");
        editForecastInDBjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editForecastInDBjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editForecastInDBjButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        citiesJList.setBackground(new java.awt.Color(204, 204, 204));
        citiesJList.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        citiesJList.setForeground(new java.awt.Color(51, 51, 51));
        citiesJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(citiesJList);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        dateSelectionJComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateSelectionJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jScrollPane1.setViewportView(dateSelectionJComboBox);

        datejLabel.setBackground(new java.awt.Color(204, 204, 204));
        datejLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datejLabel.setForeground(new java.awt.Color(255, 255, 255));
        datejLabel.setText("Επέλεξε Ημερομηνία:");
        datejLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Επέλεξε Πόλη:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(datejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout editForecastJpanelLayout = new javax.swing.GroupLayout(editForecastJpanel);
        editForecastJpanel.setLayout(editForecastJpanelLayout);
        editForecastJpanelLayout.setHorizontalGroup(
            editForecastJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editForecastJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editForecastJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editForecastInDBjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editForecastJpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        editForecastJpanelLayout.setVerticalGroup(
            editForecastJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editForecastJpanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editForecastInDBjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editForecastJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editForecastJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editForecastInDBjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editForecastInDBjButtonActionPerformed
       
        System.out.println("EDIT forecast: " + forecast);
       
        try {
        int tmpTemperature = Integer.parseInt(editTemperatureJTextField.getText());
        int tmpHumidity = Integer.parseInt(editHumidityJTextField.getText());
        int tmpUVIndex = Integer.parseInt(editUVIndexJTextField.getText());
        int tmpWindSpeed = Integer.parseInt(editWindSpeedJTextField.getText());
        String tmpWeatherDesc = editWeatherDescJTextField.getText();
        
        if(tmpTemperature < -90 || tmpTemperature > 60){
            JOptionPane.showMessageDialog(null,
                "Επιτρεπτές Τιμές Θερμοκρασίας απο -90oC έως +60oC",
                "Λάθος Τιμή Θερμοκρασίας",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(tmpHumidity < 0 || tmpHumidity > 100){
            JOptionPane.showMessageDialog(null,
                "Επιτρεπτές Τιμές Υγρασίας απο 0% έως 100%",
                "Λάθος Τιμή Υγρασίας",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(tmpUVIndex < 0 || tmpUVIndex > 12){
            JOptionPane.showMessageDialog(null,
                "Επιτρεπτές Τιμές Δείκτη UV Ακτινοβολίας απο 0 έως 12",
                "Λάθος Τιμή Δείκτη UV Ακτινοβολίας",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(tmpWindSpeed < 0 || tmpWindSpeed > 407){
            JOptionPane.showMessageDialog(null,
                "Επιτρεπτές Τιμές Ταχύτητας Ανέμου σε kmp απο 0 έως +407",
                "Λάθος Τιμή Ταχύτητας; Ανέμου",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(tmpWeatherDesc.isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Συμπληρώστε μία Λεκτική Περιγραφή",
                "Λάθος Λεκτική Πειργραφή Καιρού",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.forecast.setTemperature(tmpTemperature);
        this.forecast.setHumidity(tmpHumidity);
        this.forecast.setUvindex(tmpUVIndex);
        this.forecast.setWindspeed(tmpWindSpeed);        
        this.forecast.setWeatherdescription(tmpWeatherDesc);

            try {                       
                this.jpaLinker.updateForecastTableInDatabase(jpaLinker.getCityForecastController(), forecast);
            } catch(Exception e) {          
                System.out.println("Error: " + e.getLocalizedMessage());
            }
        
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,
                                         "Invalid input! Please enter numeric values.",
                                         "Validation Error",
                                         JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_editForecastInDBjButtonActionPerformed
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> citiesJList;
    private javax.swing.JComboBox<String> dateSelectionJComboBox;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JButton editForecastInDBjButton;
    private javax.swing.JPanel editForecastJpanel;
    private javax.swing.JLabel editHumidityJLabel;
    private javax.swing.JTextField editHumidityJTextField;
    private javax.swing.JLabel editTemperatureJLabel;
    private javax.swing.JTextField editTemperatureJTextField;
    private javax.swing.JTextField editUVIndexJTextField;
    private javax.swing.JLabel editUvIndexJLabel;
    private javax.swing.JTextField editWeatherDescJTextField;
    private javax.swing.JLabel editWeatherDescriptionJLabel;
    private javax.swing.JLabel editWindJLabel;
    private javax.swing.JTextField editWindSpeedJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
