/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eap.pli24.weatherapp.gui;

import com.eap.pli24.weatherapp.db.City;
import com.eap.pli24.weatherapp.db.MyJpaLinker;
import com.eap.pli24.weatherapp.pdf.PdfFileCreator;
import java.awt.Dimension;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;


public class CityForecastStatisticsForm extends javax.swing.JFrame {

    
    List <City> citiesViews;
    private MyJpaLinker jpaLinker = new MyJpaLinker();
    
    /**
     * Creates new form CityForecastStatisticsFrom
     */
    public CityForecastStatisticsForm() {
        initComponents();
        
        setTitle("Στατιστικά Αναζήτησης Πόλεων");
        setPreferredSize(new Dimension(600,500));
        pack();

        this.setLocationRelativeTo(null);

        citiesViews = this.jpaLinker.getCitiesViews();


        TableModel tb = new AbstractTableModel() {
            private final String[] columnNames = {"Πόλη", "Προβολές"};

            @Override
            public int getRowCount() {
                return citiesViews.size();
            }

            @Override
            public int getColumnCount() {
                return columnNames.length;
            }

            @Override
            public String getColumnName(int columnIndex) {
                return columnIndex == 0 ? "Πόλη" : "Προβολές";
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? String.class : Integer.class;
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                return columnIndex == 0 ? citiesViews.get(rowIndex).getName() : citiesViews.get(rowIndex).getViews();
            }
        };
        //Στοίχιση στο κέντρο
        citiesStatisticsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        centerRenderer.setVerticalTextPosition(javax.swing.JLabel.CENTER);
        citiesStatisticsTable.setDefaultRenderer(Object.class, centerRenderer);
        
        citiesStatisticsTable.setModel(tb);

       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statisticsTablejScrollPane = new javax.swing.JScrollPane();
        citiesStatisticsTable = new javax.swing.JTable();
        pdfButtonPanel = new javax.swing.JPanel();
        pdfButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 102, 0));

        statisticsTablejScrollPane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        citiesStatisticsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        statisticsTablejScrollPane.setViewportView(citiesStatisticsTable);

        pdfButtonPanel.setBackground(new java.awt.Color(0, 102, 0));

        pdfButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pdfButton.setText("Εκτύπωση σε Pdf");
        pdfButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pdfButtonPanelLayout = new javax.swing.GroupLayout(pdfButtonPanel);
        pdfButtonPanel.setLayout(pdfButtonPanelLayout);
        pdfButtonPanelLayout.setHorizontalGroup(
            pdfButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pdfButtonPanelLayout.setVerticalGroup(
            pdfButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdfButtonPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pdfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Πίνακας Στατιστικών Αναζητήσεων Καιρικών Δεδεομένων Πόλεων με Φθίνουσα Σειρά Προβολών");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statisticsTablejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                            .addComponent(pdfButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(statisticsTablejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pdfButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfButtonActionPerformed
        // Δημιουργία διαλόγου αποθήκευσης
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf",
                "pdf");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle(
                "Επιλέξτε που θα αποθηκευτεί το PDF αρχείο σας");

        // Έλεγχος επιλογής χρήστη
        int userSelection = fileChooser.showSaveDialog(this);
        // Συνεχίζουμε την εκτέλεση της μεθόδου μόνο οταν ο χρήστης
        // επιλέξει "Αποθήκευση"
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        // Αποθηκέυουμε στην μεταβλητή path, την διαδρομή του αρχείου
        // αποθήκευσης που επίλεξε ο χρήστης
        String path = "";
        try {
            path = fileChooser.getSelectedFile().getCanonicalPath();
        } catch (IOException e) {
            System.out.println("Error at saving the pdf: " + e.getMessage());
        }
        if (!path.isEmpty()) {
            if (PdfFileCreator.createPDFFile(this.jpaLinker.getCitiesViews(), path)) {
                JOptionPane.showMessageDialog(this, "Το αρχείο pdf αποθηκεύτηκε επιτυχώς", "Αποθήκευση PDF",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_pdfButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable citiesStatisticsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pdfButton;
    private javax.swing.JPanel pdfButtonPanel;
    private javax.swing.JScrollPane statisticsTablejScrollPane;
    // End of variables declaration//GEN-END:variables
}
